name: Build and Push Helm Chart
on:
  push:
    branches:
      - main
      - staging
    tags:
      - 1.*
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gather metadata for versioning
        id: version
        run: |
          # Get branch name
          if [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            BRANCH_NAME=staging
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            BRANCH_NAME=dev
          fi

          # Get latest tag
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "1.0.0")

          # Declare version
          echo "version=${LATEST_TAG}-${BRANCH_NAME}" >> $GITHUB_OUTPUT

          # Report
          echo "Branch: ${BRANCH_NAME}"
          echo "Tag: ${LATEST_TAG}"
          echo "Version: ${LATEST_TAG}-${BRANCH_NAME}-"

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Package Helm chart
        run: |
          helm package helm/resume-web/ \
          --version ${{ steps.version.outputs.version }} \
          --destination ./helm-packages

      - name: Log in to Helm repository
        run: |
          helm registry login gitea.copeworks.com.ar \
            -u ${{ gitea.actor }} \
            -p ${{ secrets.DOCKER_TOKEN }}

      - name: Push Helm chart to OCI registry
        run: |
          helm push ./helm-packages/resume-web-${{ steps.version.outputs.tag }}-${{ steps.tags.outputs.tag_suffix }}.tgz \
            oci://gitea.copeworks.com.ar/isma_font

      - name: Create Git tag
        if: success()
        run: |
          git config user.email "ci_operator@gitea.copeworks.com.ar"
          git config user.name "CI Operator"
          git tag -a ${{ steps.version.outputs.tag }} -m "Release ${{ steps.version.outputs.tag }}" || true
          git push origin ${{ steps.version.outputs.tag }} || true
